#!/bin/sh

TEMPLATES=(markdown latex odt asciidoc gpasm avr tddlight yesod inkscape)
TEMPLATES_LOCATION=/usr/local/share/made/templates


function args_parsing()
{
    if [[ $# -lt 1 ]];
    then
        show_help
        exit 1
    fi

    opt_force=1
    for i in $@
    do
        if [[ "$i" == "-f" ]] || [[ "$i" == "--force" ]];
        then
            opt_force=0
        fi
    done

    case $1 in
        -l|--list)
            list_templates
            ;;
        -h|--help)
            show_help
            ;;
        *)
            if template_exists "$1";
            then
                spawn_makefile "$1" "$opt_force"
            else
                echo
                echo "[!] Template for $1 does not exists"
                echo
                exit 1
            fi
    esac
}


function template_exists()
{
    for i in "${TEMPLATES[@]}"
    do
        if [[ "$1" == "$i" ]];
        then
            return 0;
        fi
    done
    return 1;
    echo
}


function list_templates()
{
    echo "Available templates:"
    echo
    for i in $TEMPLATES_LOCATION/*
    do
        echo -e "\t* $(basename $i)"
    done
}


function show_help()
{
    echo
    echo "Usage: made [OPTION] [TEMPLATE]"
    echo "Create a TEMPLATE Makefile in the current directory"
    echo
    echo " -l, --list        List available templates"
    echo " -h, --help        Show this help"
    echo " -f, --force       Overwrite existing Makefile"
    echo
}


function spawn_makefile()
{
    if [[ -f "./Makefile" ]] && [[ $2 -ne 0 ]]
    then
        echo
        echo "[!] A Makefile already exists, use -f option to overwrite"
        echo
        exit 1
    else
        cp "$TEMPLATES_LOCATION/$1/Makefile" ./
    fi
}


args_parsing "$@"
