#!/bin/sh

TEMPLATES=(markdown latex)
TEMPLATES_LOCATION=/usr/share/made/templates


function args_parsing()
{
    case $1 in
        -l|--list)
            list_templates
            ;;
        -h|--help)
            show_help
            ;;
        *)
            if template_exists "$1";
            then
                spawn_makefile "$1"
            else
                echo
                echo "[!] Template for $1 does not exists"
                echo
                exit 1
            fi
    esac
}


function template_exists()
{
    for i in "${TEMPLATES[@]}"
    do
        if [[ "$1" == "$i" ]];
        then
            return 0;
        fi
    done
    return 1;
    echo
}


function list_templates()
{
    echo "Templates:"
    echo
    for i in "${TEMPLATES[@]}"
    do
        echo "$i"
    done
}


function show_help()
{
    echo
    echo "Usage: $0 [OPTION] [TEMPLATE]"
    echo "Create a TEMPLATE Makefile in the current directory"
    echo
    echo " -l, --list        List available templates"
    echo " -h, --help        Show this help"
    echo " -f, --force       Overwrite existing Makefile"
    echo
}


function spawn_makefile()
{
    cp "$TEMPLATES_LOCATION/$1/Makefile" ./
}


args_parsing "$@"
